project:
  type: book

execute: 
  freeze: true

book:
  title: "Álgebra Computacional com GAP"
  subtitle: "Minicurso na Escola de Álgebra, 2024"
  author: "Csaba Schneider e Igor Lima"
  date: "Criado e atualizado maio-julho de 2024"
  chapters:
    - index.qmd
    - arith.qmd
    - list_mat_perm.qmd
    - estrut.qmd
    - ling.qmd
    - erdos_woods.qmd
    - collatz.qmd
    - aliquot.qmd
    - rsa.qmd
    - commutators.qmd
    - cubo.qmd
    - centralizers.qmd
    - semidirect.qmd
    - genord.qmd
    - algebras.qmd
    - groebner1.qmd
    - grafos.qmd

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    fontsize: 12pt
    grid:
      sidebar-width: 200px
      body-width: 800px
      margin-width: 600px
      gutter-width: 1.5rem