---
title: "Uma questão sobre centralizadores"
number-sections: true
lang: pt-BR
---

## Os fundamentos teóricos

:::{.problem}
Recordamos que o centralizador de um elemento $x$ em um grupo $G$ é definido por 
$$
C_{G}(x) = \{g \in G | \ gx=xg \}.
$$

Denote por $\mbox{Cent}(G)$ o conjunto de todos os centralizadores de elementos de $G$. 

Por exemplo, se $G=S_3$, então temos os seguintes centralizadores dos seus elementos: 

| elemento      | 1     | $(1,2)$ | $(1,3)$ | $(2,3)$ | $(1,2,3)$ | $(1,3,2)$ | 
| ---           |---    | ---     | ---     | ---     | ---       | ---    | 
| centralizador | $S_3$ | $\left<(1,2)\right>$ | $\left<(1,3)\right>$ | $\left<(2,3)\right>$ | $\left<(1,2,3)\right>$ | $\left<(1,2,3)\right>$

Note que o subgrupo $\left<(1,2,3)\right>$ aparece duas vezes, então 
$$
\mbox{Cent}(S_3)=\{S_3,\left<(1,2)\right>, \left<(1,3)\right>, \left<(2,3)\right>, \left<(1,2,3)\right>\}
$$ 
e
$$
|\mbox{cent}(S_3)|=5.
$$

O estudo de $\mbox{Cent}(G)$ tem chamado a atenção de muitos pesquisadores. As duas principais motivações para se estudar $\mbox{Cent}(G)|$ é responder essencialmente duas questões:


1. Dado um grupo $G$, o que se pode dizer sobre $|\mbox{Cent}(G)|$?
2. Se é conhecido o valor de $|\mbox{Cent}(G)|$, o que se pode dizer a respeito do grupo $G$?
    

Neste projeto, queremos usar o `GAP` para resolver algumas questões para grupos simples finitos.
:::

<!--:::{.subexample}
Vamos calcular o conjunto de centralizadores do grupo simétrico $S_3$ e alternado $A_4$. 

```matlab
ap> s3 := SymmetricGroup( 3 );
Sym( [ 1 .. 3 ] )
gap> List( s3, x->Centralizer( s3, x ));         
[ Group([ (1,3), (2,3) ]), Group([ (2,3) ]), Group([ (1,3) ]), 
  Group([ (1,3,2) ]), Group([ (1,2,3) ]), Group([ (1,2) ]) ]
gap> Length( last );                              
6
gap> Set( s3, x->Centralizer( s3, x )); 
[ Group([ (2,3) ]), Group([ (1,3), (2,3) ]), Group([ (1,2) ]), 
  Group([ (1,3,2) ]), Group([ (1,3) ]) ]
gap> Length( last );
5
gap> a4 := AlternatingGroup( 4 );
Alt( [ 1 .. 4 ] )
gap> List( a4, x->Centralizer( a4, x ));
[ Group([ (1,2,4), (1,3,4) ]), Group([ (2,4,3) ]), Group([ (2,3,4) ]), 
  Group([ (1,4,3) ]), Group([ (1,2)(3,4), (1,4)(2,3) ]), Group([ (1,4,2) ]), 
  Group([ (1,3,4) ]), Group([ (1,3,2) ]), Group([ (1,2)(3,4), (1,3)(2,4) ]), 
  Group([ (1,2,4) ]), Group([ (1,3)(2,4), (1,2)(3,4) ]), Group([ (1,2,3) ]) ]
gap> Length( last );
12
gap> Set( a4, x->Centralizer( a4, x )); 
[ Group([ (2,4,3) ]), Group([ (1,2,4), (1,3,4) ]), 
  Group([ (1,2)(3,4), (1,4)(2,3) ]), Group([ (1,3,2) ]), Group([ (1,4,2) ]), 
  Group([ (1,4,3) ]) ]
gap> Length( last );
6
```
Obtivemos que $|\mbox{Cent}(S_3)=5|$ e $|\mbox{Cent}(A_4)|=6$. Note como usamos a função `Set` em vez da função `List` para obter cada centralizador apenas uma vez.
:::
-->

## Tarefa 1

:::{.subproblem}

Vamos determinar o centralizador de um elemento em um grupo. Considere o seguinte exemplo.

```matlab
gap> G := AlternatingGroup( 5 );
Alt( [ 1 .. 5 ] )
gap> x := (1,2,3);
(1,2,3)
gap> Cx := Centralizer( G, x );
Group([ (1,2,3) ])
gap> Size( Cx );
3
```

Seguindo o exemplo em cima, determine os seguintes centralizadores $C_G(x)$. 

1. $G=S_6$, $x=(1,2,3)(4,5,6)$. 
2. $G=D_8$ (diedral de ordem 8) e $x$ é uma rotação por $90$ graus.
3. $G=\mbox{GL}(2,5)$ e $x$ é a matriz diagonal com $(2,3)$ na diagonal principal.
:::

:::{.hint}
Consulte @sec-grupos para ver como definir o grupo `GL` e o grupo diedral.
:::

## Exploração interativa 

:::{.subexample}
Para investigar o problema em cima, nós precisamos determinar o conjunto dos centralizadores em um grupo dado. Vamos fazer esta computação com o grupo $S_5$. 

```gap
gap> G := SymmetricGroup( 3 );
Sym( [ 1 .. 3 ] )
gap> cent := List( G, x->Centralizer( G, x ));
[ Group([ (1,3), (2,3) ]), Group([ (2,3) ]), Group([ (1,3) ]), Group([ (1,3,2) ]), 
  Group([ (1,2,3) ]), Group([ (1,2) ]) ]
gap> cent[5] = cent[6];
false
gap> cent[4] = cent[5];
true
gap> cent_set := Set( G, x->Centralizer( G, x ));
[ Group([ (2,3) ]), Group([ (1,3), (2,3) ]), Group([ (1,2) ]), Group([ (1,3,2) ]), 
  Group([ (1,3) ]) ]
gap> Size( cent );
6
gap> Size( cent_set );
5
```
Ou seja, $S_3$ possui 5 centralizadores (como foi visto em cima). Note que usamos a função `Set` que vai devolver um conjunto; ou seja, todo elemento do output será aparece apenas uma vez.
:::

## Tarefa 3

:::{.subproblem}
Escreva uma função `Cent(G)` para computar o conjunto de todos os centralizadores de elementos de um grupo $G$ dado. Use a função `Centralizer(G,x)` ([manual](https://docs.gap-system.org/doc/ref/chap35.html#X7A2BF4527E08803C)). 



Sua função deve verificar:
```matlab
gap> Cent( SymmetricGroup( 3 ));                  
[ Group([ (2,3) ]), Group([ (1,3), (2,3) ]), Group([ (1,2) ]), 
  Group([ (1,3,2) ]), Group([ (1,3) ]) ]
gap> Cent( AlternatingGroup( 4 ));
[ Group([ (2,4,3) ]), Group([ (1,2,4), (1,3,4) ]), 
  Group([ (1,2)(3,4), (1,4)(2,3) ]), Group([ (1,3,2) ]), Group([ (1,4,2) ]), 
  Group([ (1,4,3) ]) ]
gap> Cent( SmallGroup( 16,7 ));   
[ Group([ f1, f4 ]), Group([ f2, f4 ]), 
  <pc group of size 16 with 4 generators>, Group([ f1*f2, f3, f4 ]), 
  Group([ f1*f3, f4 ]), Group([ f2*f3, f4 ]) ]
gap> Size(Cent(AlternatingGroup(6)));
137
gap> Size(Cent(AlternatingGroup(5)));
807
gap> Size(Cent(PSL(2,7)));
79
gap> Size(Cent(PSL(3,3)));
1185
gap> Size(Cent(DihedralGroup(8)));
4
gap> Size(SmallGroup(16,7));
6
gap> Size(Cent(MathieuGroup(11)));
2081
```
:::

<!--## Tarefa 4

:::{.subproblem}
A lista a seguir possui somente ordens de grupos simples não abelianos (com repetição):
```matlab
[60, 168, 360, 504, 660, 1092, 2448, 2520, 3420, 4080, 5616, 6048, 6072, 7800, 7920, 
 9828, 12180, 14880, 20160, 20160, 25308, 25920, 29120, 32736, 34440, 39732, 51888, 
 58800, 62400, 74412, 95040, 102660, 113460, 126000, 150348]
``` 

Explore a função `AllSmallNonabelianSimpleGroups([60..n])`, para $n$ no conjunto acima. Por exemplo:

```matlab
gap> AllSmallNonabelianSimpleGroups([60..20160]);
[ A5, PSL(2,7), A6, PSL(2,8), PSL(2,11), PSL(2,13), PSL(2,17), A7, PSL(2,19), PSL(2,16), PSL(3,3), PSU(3,3), PSL(2,23), PSL(2,25), M11, PSL(2,27), PSL(2,29), PSL(2,31), A8, PSL(3,4)]
```
:::
-->

## Tarefa 4

:::{.subproblem}
Agora você precisa responder a seguinte questão 

1. [Questão de Ashrafi e Taeri] Sejam $G$ e $H$ grupos simples não abelianos. É verdade que se $|\mbox{Cent}(G)| = |\mbox{Cent}(H)|$, então $G$ é isomorfo a $H$?
:::

:::{.hint}
Is grupos simples não abelianos podem ser acessos usando a função `AllSmallNonabelianSimpleGroups( list )` 
onde `list` é uma lista de números naturais. A função devolve a lista dos grupos simples abelianos cuja ordem está na lista `list`. Por exemplo:
```matlab
gap> AllSmallNonabelianSimpleGroups( [1..200] );
[ A5, PSL(2,7) ]
```
Ou seja, existem apenas $2$ grupos simples com ordem entre $1$ e $200$; nomeadamente $A_5$ e $\mbox{PSL}(2,7)$. Use a função  `AllSmallNonabelianSimpleGroups` para gerar grupos simples e compare os seus números de centralizadores. 
:::
<!--Compute $|Cent(PSL(2,23)|$ e $|Cent(A7)|$ e verifique se esses esses grupos são isomorfos.-->

## Tarefa 5

:::{.subproblem}
E se restringirmos a função para sabermos a quantidade dos centralizadores abelianos ou dos centralizadores não abelianos de um grupo? Será que se dois grupos simples não abelianos tiverem a mesma quantidade de centralizadores abelianos (ou não abelianos) de elementos, esses grupos são necessariamente isomorfos? 

1. Escreva uma nova versão da função `Cent( G )` que aceita, além do grupo `G`, um argumento opcional (veja @sec-functions) que pode ser `true` ou `false`. Se o valor do argumento opcional for `true`, a função devolve o conjunto dos centralizadores abelianos; se o valor for `false`, devolve o conjunto dos centralizadores não abelianos.
```matlab
gap> cent( AlternatingGroup( 4 ));
[ Group([ (2,4,3) ]), Group([ (1,2,4), (1,3,4) ]), 
  Group([ (1,2)(3,4), (1,4)(2,3) ]), Group([ (1,3,2) ]), Group([ (1,4,2) ]), 
  Group([ (1,4,3) ]) ]
gap> cent( AlternatingGroup( 4 ), true );
[ Group([ (2,4,3) ]), Group([ (1,2)(3,4), (1,4)(2,3) ]), Group([ (1,3,2) ]), 
  Group([ (1,4,2) ]), Group([ (1,4,3) ]) ]
gap> cent( AlternatingGroup( 4 ), false );
[ Group([ (1,2,4), (1,3,4) ]) ]
```
2. Ache dois grupos simples não abelianos não isomorfos que têm o mesmo número de centralizadores abelianos ou não abelianos.
:::

<!--
cent := function ( G, arg... )
    if Length( arg ) = 0 then
        return Set( G, function ( x )
                return Centralizer( G, x );
            end );
    fi;
    if arg[1] then
        return Filtered( Set( G, function ( x )
                  return Centralizer( G, x );
              end ), IsAbelian );
    else
        return Filtered( Set( G, function ( x )
                  return Centralizer( G, x );
              end ), function ( z )
                return not IsAbelian( z );
            end );
    fi;
    return;
end
-->

:::{.hint}
Funções com argumentos opcionais foram tratadas na @sec-functions. 
:::

## Tarefa 6

:::{.subproblem}
Nesta próxima tarefa, vamos usar o conceito de grupos isoclínicos (desenvolvido por P. Hall em [seu artigo influenciador](https://www.degruyter.com/document/doi/10.1515/crll.1940.182.130/pdf) de 1940). Dois grupos $G$ e $H$ são ditos isoclínicos se existem dois isomorfismos 
$$
\phi: \frac{G}{Z(G)} \rightarrow \frac{H}{Z(H)}\quad \mbox{e} \quad\psi: G' \rightarrow H'
$$ 
tais que se 
$$
\phi(g_1Z(G))=h_1Z(H)\quad\mbox{e} \quad\phi(g_2Z(G))=h_2Z(H)
$$
para $g_1,g_2 \in G$ e $h_1,h_2 \in H$, então $\psi([g_1,g_2])= [h_1,h_2]$. É possível mostrar que isoclinismo é uma relação de equivalência e que grupos abelianos são isoclínicos ao grupo trivial. 


Por exemplo, pode se verificar que o grupo dihedral $D_8$ e o grupo de quaternions $Q_8$ são isoclínicos, mas os grupos $D_8$ e $D_{10}$ não são.

```matlab
gap> LoadPackage( "xmod" );
true
gap> f := Isoclinism( DihedralGroup(8), QuaternionGroup(8));
[ [ f1, f2 ] -> [ f2, f1*f2 ], [ f3 ] -> [ y2 ] ]
gap> Isoclinism( DihedralGroup( 8 ), DihedralGroup( 10 ));
fail
```

M. Zarrin usou o isoclinismo para estender os resultados sobre centralizados de elementos para grupos infinitos. Em particular, ele provou que se $G$ e $H$ são isoclínicos, então $|\mbox{Cent}(G)| = |\mbox{Cent}(H)|$.
Nesta tarefa vamos verificar a seguinte questão de [Khoramshahi and M. Zarrin](https://www.worldscientific.com/doi/10.1142/S0219498821500122).

- Ache dois grupos $G$ e $H$ tal que $|\mbox{Cent}(G)|=|\mbox{Cent}(H)|$, $|H|=|G|$, $|G'|=|H'|$, mas  $G$ e $H$ não são isoclínicos.
- Khoromshahi e Zarrin mostrou que se $G$ e $H$ são como no item anterior, então   $|\mbox{Cent}(G)|\leq 5$. Ache exemplos com $|\mbox{Cent}(G)|=6$ para verificar que esta quota superior não pode ser melhorada.  
:::

:::{.hint}
Para gerar os candidatos entre os possíveis grupos, use a função `AllSmallGroups`. Por exemplo, pode gerar os grupos de ordem entre $1$ e $20$ com 6 centralizadores com o seguinte código:
```matlab
gap> AllSmallGroups( Size, [1..20], x->Size( cent( x )) = 6 );
[ <pc group of size 12 with 3 generators>, 
  <pc group of size 16 with 4 generators>, 
  <pc group of size 16 with 4 generators>, 
  <pc group of size 16 with 4 generators> ]
```
:::


<!--

gap> f:=function(g)                               
> local x;                                     
> return Set(List(g,x->Centralizer(g,x))); end;
function( g ) ... end
gap> f(SymmetricGroup(3));
[ Group([ (2,3) ]), Group([ (1,3), (2,3) ]), Group([ (1,2) ]), Group([ (1,3,2) ]), Group([ (1,3) ]) ]
gap> Size(last);
5
-->